
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_1?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: kemao_1
      password: 1234

   #配置Redis的连接信息
   redis:
      # 这里换自己的IP
      host: 47.107.78.162
      port: 6379
      database: 15
server.port: 8008
